@if "%~1"=="" goto default
@if "%~1"=="clean" goto clean
@echo unknown option: %1
@exit /b 1
:clean
del /q *.obj ..\volvox.* libvolvox.exp libvolvox.lib ..\libvolvox.dll
@exit /b 0
:default
@for %%f in (codegen.cc token.cc lexer.cc parser.cc types.cc main.cc) do cl /MP /we"4238" /GS /Zc:rvalueCast /W4 /wd"4201" /wd"4189" /wd"4141" /wd"4146" /wd"4244" /wd"4267" /wd"4291" /wd"4351" /wd"4456" /wd"4457" /wd"4458" /wd"4459" /wd"4503" /wd"4624" /wd"4722" /wd"4100" /wd"4127" /wd"4512" /wd"4505" /wd"4610" /wd"4510" /wd"4702" /wd"4245" /wd"4706" /wd"4310" /wd"4701" /wd"4703" /wd"4389" /wd"4611" /wd"4805" /wd"4204" /wd"4577" /wd"4091" /wd"4592" /wd"4319" /wd"4709" /wd"4324" /Zc:wchar_t /I"C:\Users\uwekr\llvm-project\build\include" /I"C:\Users\uwekr\llvm-project\llvm\include" /Gm- /O2 /Ob2 /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_HAS_EXCEPTIONS=0" /D "GTEST_HAS_RTTI=0" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_NONSTDC_NO_DEPRECATE" /D "_CRT_NONSTDC_NO_WARNINGS" /D "_SCL_SECURE_NO_DEPRECATE" /D "_SCL_SECURE_NO_WARNINGS" /D "UNICODE" /D "_UNICODE" /D "__STDC_CONSTANT_MACROS" /D "__STDC_FORMAT_MACROS" /D "__STDC_LIMIT_MACROS" /D "CMAKE_INTDIR=\"Release\"" /errorReport:prompt /WX- /Zc:forScope /Gd /Oi /MD /std:c++20 /nologo /diagnostics:column /c /I"C:\Program Files\LLVM\include" /EHs-c- %%f

@for %%f in (..\lib\str.cc) do cl /DLL /MP /we"4238" /GS /Zc:rvalueCast /W4 /wd"4201" /wd"4189" /wd"4141" /wd"4146" /wd"4244" /wd"4267" /wd"4291" /wd"4351" /wd"4456" /wd"4457" /wd"4458" /wd"4459" /wd"4503" /wd"4624" /wd"4722" /wd"4100" /wd"4127" /wd"4512" /wd"4505" /wd"4610" /wd"4510" /wd"4702" /wd"4245" /wd"4706" /wd"4310" /wd"4701" /wd"4703" /wd"4389" /wd"4611" /wd"4805" /wd"4204" /wd"4577" /wd"4091" /wd"4592" /wd"4319" /wd"4709" /wd"4324" /Zc:wchar_t /I"C:\Users\uwekr\llvm-project\build\include" /I"C:\Users\uwekr\llvm-project\llvm\include" /Gm- /O2 /Ob2 /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_HAS_EXCEPTIONS=0" /D "GTEST_HAS_RTTI=0" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_NONSTDC_NO_DEPRECATE" /D "_CRT_NONSTDC_NO_WARNINGS" /D "_SCL_SECURE_NO_DEPRECATE" /D "_SCL_SECURE_NO_WARNINGS" /D "UNICODE" /D "_UNICODE" /D "__STDC_CONSTANT_MACROS" /D "__STDC_FORMAT_MACROS" /D "__STDC_LIMIT_MACROS" /D "CMAKE_INTDIR=\"Release\"" /errorReport:prompt /WX- /Zc:forScope /Gd /Oi /MD /std:c++20 /nologo /diagnostics:column /c /I"C:\Program Files\LLVM\include" /EHs-c- %%f

@for %%f in (..\lib\map.cc getopt.c) do cl /DLL /TC /MP /we"4238" /GS /Zc:rvalueCast /W4 /wd"4201" /wd"4189" /wd"4141" /wd"4146" /wd"4244" /wd"4267" /wd"4291" /wd"4351" /wd"4456" /wd"4457" /wd"4458" /wd"4459" /wd"4503" /wd"4624" /wd"4722" /wd"4100" /wd"4127" /wd"4512" /wd"4505" /wd"4610" /wd"4510" /wd"4702" /wd"4245" /wd"4706" /wd"4310" /wd"4701" /wd"4703" /wd"4389" /wd"4611" /wd"4805" /wd"4204" /wd"4577" /wd"4091" /wd"4592" /wd"4319" /wd"4709" /wd"4324" /Zc:wchar_t /I"C:\Users\uwekr\llvm-project\build\include" /I"C:\Users\uwekr\llvm-project\llvm\include" /Gm- /O2 /Ob2 /Zc:inline /fp:precise /D "BUILD_MAP" /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_HAS_EXCEPTIONS=0" /D "GTEST_HAS_RTTI=0" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_NONSTDC_NO_DEPRECATE" /D "_CRT_NONSTDC_NO_WARNINGS" /D "_SCL_SECURE_NO_DEPRECATE" /D "_SCL_SECURE_NO_WARNINGS" /D "UNICODE" /D "_UNICODE" /D "__STDC_CONSTANT_MACROS" /D "__STDC_FORMAT_MACROS" /D "__STDC_LIMIT_MACROS" /D "CMAKE_INTDIR=\"Release\"" /errorReport:prompt /WX- /Zc:forScope /Gd /Oi /MD /std:c++20 /nologo /diagnostics:column /c /I"C:\Program Files\LLVM\include" /EHs-c- %%f

link /DLL /out:libvolvox.dll /EXPORT:map_string_new_map /EXPORT:map_string_insert /EXPORT:map_string_tag_insert /EXPORT:map_string_get /EXPORT:_ZN6volvox6fprintEiPKcPKNS_6RtTypeEz /EXPORT:_ZN6volvox8fprintlnEiPKcPKNS_6RtTypeEz /EXPORT:_ZN6volvox5printEPKcPKNS_6RtTypeEz /EXPORT:_ZN6volvox7printlnEPKcPKNS_6RtTypeEz str.obj map.obj

move libvolvox.dll ..

cl /DLL /MP /we"4238" /GS /Zc:rvalueCast /W4 /wd"4201" /wd"4189" /wd"4141" /wd"4146" /wd"4244" /wd"4267" /wd"4291" /wd"4351" /wd"4456" /wd"4457" /wd"4458" /wd"4459" /wd"4503" /wd"4624" /wd"4722" /wd"4100" /wd"4127" /wd"4512" /wd"4505" /wd"4610" /wd"4510" /wd"4702" /wd"4245" /wd"4706" /wd"4310" /wd"4701" /wd"4703" /wd"4389" /wd"4611" /wd"4805" /wd"4204" /wd"4577" /wd"4091" /wd"4592" /wd"4319" /wd"4709" /wd"4324" /Zc:wchar_t /I"C:\Users\uwekr\llvm-project\build\include" /I"C:\Users\uwekr\llvm-project\llvm\include" /Gm- /O2 /Ob2 /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_HAS_EXCEPTIONS=0" /D "GTEST_HAS_RTTI=0" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_NONSTDC_NO_DEPRECATE" /D "_CRT_NONSTDC_NO_WARNINGS" /D "_SCL_SECURE_NO_DEPRECATE" /D "_SCL_SECURE_NO_WARNINGS" /D "UNICODE" /D "_UNICODE" /D "__STDC_CONSTANT_MACROS" /D "__STDC_FORMAT_MACROS" /D "__STDC_LIMIT_MACROS" /D "CMAKE_INTDIR=\"Release\"" /errorReport:prompt /WX- /Zc:forScope /Gd /Oi /MD /std:c++20 /nologo /diagnostics:column /c /I"C:\Program Files\LLVM\include" /EHs-c- ..\lib\emutls.c

link /out:..\volvox.exe /MANIFEST /NXCOMPAT /MANIFEST /NXCOMPAT token.obj lexer.obj parser.obj codegen.obj main.obj types.obj emutls.obj getopt.obj libvolvox.lib /DYNAMICBASE "C:\Program Files\LLVM\lib\LLVMMCJIT.lib" "C:\Program Files\LLVM\lib\LLVMOrcJIT.lib" "C:\Program Files\LLVM\lib\LLVMPasses.lib" "C:\Program Files\LLVM\lib\LLVMObjCARCOpts.lib" "C:\Program Files\LLVM\lib\LLVMCoroutines.lib" "C:\Program Files\LLVM\lib\LLVMipo.lib" "C:\Program Files\LLVM\lib\LLVMInstrumentation.lib" "C:\Program Files\LLVM\lib\LLVMVectorize.lib" "C:\Program Files\LLVM\lib\LLVMLinker.lib" "C:\Program Files\LLVM\lib\LLVMIRReader.lib" "C:\Program Files\LLVM\lib\LLVMAsmParser.lib" "C:\Program Files\LLVM\lib\LLVMFrontendOpenMP.lib" "C:\Program Files\LLVM\lib\LLVMJITLink.lib" "C:\Program Files\LLVM\lib\LLVMExecutionEngine.lib" "C:\Program Files\LLVM\lib\LLVMRuntimeDyld.lib" "C:\Program Files\LLVM\lib\LLVMOrcTargetProcess.lib" "C:\Program Files\LLVM\lib\LLVMOrcShared.lib" "C:\Program Files\LLVM\lib\LLVMX86Disassembler.lib" "C:\Program Files\LLVM\lib\LLVMX86AsmParser.lib" "C:\Program Files\LLVM\lib\LLVMX86CodeGen.lib" "C:\Program Files\LLVM\lib\LLVMCFGuard.lib" "C:\Program Files\LLVM\lib\LLVMGlobalISel.lib" "C:\Program Files\LLVM\lib\LLVMX86Desc.lib" "C:\Program Files\LLVM\lib\LLVMX86Info.lib" "C:\Program Files\LLVM\lib\LLVMMCDisassembler.lib" "C:\Program Files\LLVM\lib\LLVMSelectionDAG.lib" "C:\Program Files\LLVM\lib\LLVMAsmPrinter.lib" "C:\Program Files\LLVM\lib\LLVMDebugInfoMSF.lib" "C:\Program Files\LLVM\lib\LLVMDebugInfoDWARF.lib" "C:\Program Files\LLVM\lib\LLVMCodeGen.lib" "C:\Program Files\LLVM\lib\LLVMTarget.lib" "C:\Program Files\LLVM\lib\LLVMScalarOpts.lib" "C:\Program Files\LLVM\lib\LLVMInstCombine.lib" "C:\Program Files\LLVM\lib\LLVMAggressiveInstCombine.lib" "C:\Program Files\LLVM\lib\LLVMTransformUtils.lib" "C:\Program Files\LLVM\lib\LLVMBitWriter.lib" "C:\Program Files\LLVM\lib\LLVMAnalysis.lib" "C:\Program Files\LLVM\lib\LLVMProfileData.lib" "C:\Program Files\LLVM\lib\LLVMObject.lib" "C:\Program Files\LLVM\lib\LLVMTextAPI.lib" "C:\Program Files\LLVM\lib\LLVMMCParser.lib" "C:\Program Files\LLVM\lib\LLVMMC.lib" "C:\Program Files\LLVM\lib\LLVMDebugInfoCodeView.lib" "C:\Program Files\LLVM\lib\LLVMBitReader.lib" "C:\Program Files\LLVM\lib\LLVMCore.lib" "C:\Program Files\LLVM\lib\LLVMRemarks.lib" "C:\Program Files\LLVM\lib\LLVMBitstreamReader.lib" "C:\Program Files\LLVM\lib\LLVMBinaryFormat.lib" "C:\Program Files\LLVM\lib\LLVMSupport.lib" "psapi.lib" "shell32.lib" "ole32.lib" "uuid.lib" "advapi32.lib" "delayimp.lib" "-delayload:shell32.dll" "-delayload:ole32.dll" "C:\Program Files\LLVM\lib\LLVMDemangle.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "oleaut32.lib" "comdlg32.lib" /STACK:"10000000"  /MACHINE:X64 /INCREMENTAL:NO /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ERRORREPORT:PROMPT /NOLOGO /TLBID:1
