CXX := clang++
LLVMCONFIG := llvm-config
LLVMVERSION := 13
OPT := -O0 -ggdb
CXXFLAGS := $(shell $(LLVMCONFIG) --cxxflags) $(OPTF)
LDFLAGS := $(shell $(LLVMCONFIG) --ldflags --libs all) -LC:/mingw64/bin
PRJH = ../include/volvox-$(LLVMVERSION).hh
PCH = $(PRJH:%.hh=%.hh.gch)

PROG = ../volvox

OBJS := main.o lexer.o parser.o token.o codegen.o types.o

SRCS := $(OBJS:%.o=%.cc)

%.o: %.cc $(PCH)
	$(CXX) -c $(CXXFLAGS) $(OPT) -include-pch $(PCH) $<

all: $(PROG)

$(PCH): $(PRJH) ../include/VolvoxJIT-$(LLVMVERSION).h ../include/volvox.hh
	$(CXX) $(CXXFLAGS) $(OPT) $<

$(PROG): $(OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(OPT) ../lib/map.o $+ -lpthread

.PHONY: clean
clean:
	rm -f $(OBJS) $(PCH)

.PHONY: distclean
distclean:
	rm -f $(PROG) $(OBJS) *~ ../include/*~ ../include/*.gch .depend

.PHONY: depend
depend:
	$(CXX) -MM $(CXXFLAGS) $(OPT) $(SRCS) > .depend

.depend:
	$(CXX) -MM $(CXXFLAGS) $(OPT) $(SRCS) > .depend

-include .depend
