@if "%~1"=="" goto default
@if "%~1"=="clean" goto clean
@echo unknown option: %1
@exit /b 1
:clean
del /q *.obj ..\volvox.* libvolvox.exp ..\lib\libvolvox.lib ..\libvolvox.dll
@exit /b 0
:default
@for %%f in (codegen.cc token.cc lexer.cc parser.cc types.cc main.cc mangler.cc environment.cc) do @call comp.bat %%f %%~nf.obj
@for %%f in (..\wineditline\editline.c ..\wineditline\history.c ..\wineditline\fn_complete.c getopt.c) do @call comp.bat %%f %%~nf.obj /TC
@for %%f in (..\lib\str_c.c ..\lib\emutls.c) do @call comp.bat %%f %%~nf.obj /DLL /TC /D"LLVM_VERSION_MAJOR=14"
@for %%f in (..\lib\map.cc ..\lib\array.cc ..\lib\str.cc) do clang++ -O2 -target x86_64-pc-windows-gnu -fno-exceptions -DWNATIVELIB -I ..\stubinclude -c -o %%~nf.obj %%f
link /DLL /out:libvolvox.dll str.obj str_c.obj map.obj array.obj

move libvolvox.dll ..
move libvolvox.lib ..\lib

link /out:..\volvox.exe /MANIFEST:EMBED /MANIFESTINPUT:dpiutf8.manifest /NXCOMPAT token.obj lexer.obj parser.obj codegen.obj main.obj mangler.obj types.obj emutls.obj getopt.obj editline.obj fn_complete.obj history.obj ..\lib\libvolvox.lib /DYNAMICBASE "C:\Program Files\LLVM\lib\LLVMMCJIT.lib" "C:\Program Files\LLVM\lib\LLVMOrcJIT.lib" "C:\Program Files\LLVM\lib\LLVMPasses.lib" "C:\Program Files\LLVM\lib\LLVMObjCARCOpts.lib" "C:\Program Files\LLVM\lib\LLVMCoroutines.lib" "C:\Program Files\LLVM\lib\LLVMipo.lib" "C:\Program Files\LLVM\lib\LLVMInstrumentation.lib" "C:\Program Files\LLVM\lib\LLVMVectorize.lib" "C:\Program Files\LLVM\lib\LLVMLinker.lib" "C:\Program Files\LLVM\lib\LLVMIRReader.lib" "C:\Program Files\LLVM\lib\LLVMAsmParser.lib" "C:\Program Files\LLVM\lib\LLVMFrontendOpenMP.lib" "C:\Program Files\LLVM\lib\LLVMJITLink.lib" "C:\Program Files\LLVM\lib\LLVMExecutionEngine.lib" "C:\Program Files\LLVM\lib\LLVMRuntimeDyld.lib" "C:\Program Files\LLVM\lib\LLVMOrcTargetProcess.lib" "C:\Program Files\LLVM\lib\LLVMOrcShared.lib" "C:\Program Files\LLVM\lib\LLVMX86Disassembler.lib" "C:\Program Files\LLVM\lib\LLVMX86AsmParser.lib" "C:\Program Files\LLVM\lib\LLVMX86CodeGen.lib" "C:\Program Files\LLVM\lib\LLVMCFGuard.lib" "C:\Program Files\LLVM\lib\LLVMGlobalISel.lib" "C:\Program Files\LLVM\lib\LLVMX86Desc.lib" "C:\Program Files\LLVM\lib\LLVMX86Info.lib" "C:\Program Files\LLVM\lib\LLVMMCDisassembler.lib" "C:\Program Files\LLVM\lib\LLVMSelectionDAG.lib" "C:\Program Files\LLVM\lib\LLVMAsmPrinter.lib" "C:\Program Files\LLVM\lib\LLVMDebugInfoMSF.lib" "C:\Program Files\LLVM\lib\LLVMDebugInfoDWARF.lib" "C:\Program Files\LLVM\lib\LLVMCodeGen.lib" "C:\Program Files\LLVM\lib\LLVMTarget.lib" "C:\Program Files\LLVM\lib\LLVMScalarOpts.lib" "C:\Program Files\LLVM\lib\LLVMInstCombine.lib" "C:\Program Files\LLVM\lib\LLVMAggressiveInstCombine.lib" "C:\Program Files\LLVM\lib\LLVMTransformUtils.lib" "C:\Program Files\LLVM\lib\LLVMBitWriter.lib" "C:\Program Files\LLVM\lib\LLVMAnalysis.lib" "C:\Program Files\LLVM\lib\LLVMProfileData.lib" "C:\Program Files\LLVM\lib\LLVMObject.lib" "C:\Program Files\LLVM\lib\LLVMTextAPI.lib" "C:\Program Files\LLVM\lib\LLVMMCParser.lib" "C:\Program Files\LLVM\lib\LLVMMC.lib" "C:\Program Files\LLVM\lib\LLVMDebugInfoCodeView.lib" "C:\Program Files\LLVM\lib\LLVMBitReader.lib" "C:\Program Files\LLVM\lib\LLVMCore.lib" "C:\Program Files\LLVM\lib\LLVMRemarks.lib" "C:\Program Files\LLVM\lib\LLVMBitstreamReader.lib" "C:\Program Files\LLVM\lib\LLVMBinaryFormat.lib" "C:\Program Files\LLVM\lib\LLVMSupport.lib" "psapi.lib" "shell32.lib" "ole32.lib" "uuid.lib" "advapi32.lib" "delayimp.lib" "-delayload:shell32.dll" "-delayload:ole32.dll" "C:\Program Files\LLVM\lib\LLVMDemangle.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "oleaut32.lib" "comdlg32.lib" /STACK:"10000000"  /MACHINE:X64 /INCREMENTAL:NO /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ERRORREPORT:PROMPT /NOLOGO /TLBID:1
